### ISSUE TITLE
some duplicate functions...

### ISSUE THREAD

**Issue by johnadapt** [Mte90/roots-haml-compass-coffeescript#2]
Just an FYI, looks like you have some duplicate functions... not sure which one's you want to use:

Fatal error: Cannot redeclare roots_body_class() (previously declared in \lib\utils.php:19) in \lib\cleanup.php on line 119

I fixed it by removing the one in utils.php...

Fatal error: Cannot redeclare roots_get_search_form() (previously declared in \lib\utils.php:11) in \lib\cleanup.php on line 260

I fixed it by removing the one in utils.php...

Fatal error: Cannot redeclare roots_widgets_init() (previously declared in \lib\init.php:44) in \lib\widgets.php on line 27

fixed it by removing the one in widgets.php

**Comment by Mte90** [comment]
Uh thanks! i've backported the news roots version but i've not time for check the problems.
i will fix soon!

**Comment by johnadapt** [comment]
You are fast! thanks man, you rock!
