### ISSUE TITLE
issue with haml:compile

### ISSUE THREAD

**Issue by johnadapt** [Mte90/roots-haml-compass-coffeescript#3]
![image](https://cloud.githubusercontent.com/assets/2372574/5866339/27261688-a245-11e4-86b7-9ce6d9905e8a.png)

I noticed that you had said that this was an old issue that was fixed... wondering if I installed things incorrectly, or if this is a new grunt-haml-php issue...

Have tried the following to get past the compile issue:
-re-run npm install
-tried the latest version of grunt-haml-php
... I'm still a noob, so i'm searching through code, but afraid i'm not much help

**Comment by Mte90** [comment]
use the grunt-haml-php module of this repo that i've modded the original version for some fix that are not yet integrated in the original

**Comment by johnadapt** [comment]
Thanks,
I figured out that the compile issue is a windows environment issue... it's throwing the error because of how the newline "\n" or "\r\n" is being processed. I don't know where in the code, that is, or which side (the theme or grunt-haml-php) the error is coming from... so i'n not much help there.

But, I switched to my mac dev environment and the issue went away. :)

**Comment by Mte90** [comment]
*nix is the way :-)
