### ISSUE TITLE
A few more little errors

### ISSUE THREAD

**Issue by johnadapt** [Mte90/roots-haml-compass-coffeescript#4]
Just another FYI:

**** error #1 ****
Parse error: syntax error, unexpected '||' (T_BOOLEAN_OR) in /Applications/XAMPP/xamppfiles/htdocs/bm3/wp-content/themes/bethelmusic/lib/scripts.php on line 102
--- bad code ---
if (GOOGLE_ANALYTICS_ID && (!WP_DEBUG || || !current_user_can('manage_options'))) {
  add_action('wp_footer', 'roots_google_analytics', 20);
}
--- fixed code ---
if (GOOGLE_ANALYTICS_ID && (!WP_DEBUG || !current_user_can('manage_options'))) {
  add_action('wp_footer', 'roots_google_analytics', 20);
}
**** error 2 ****
Warning: file_get_contents(/wp-content/themes/bethelmusic/assets/manifest.json): failed to open stream: No such file or directory in /wp-content/themes/bethelmusic/lib/scripts.php on line 30

I followed the notes in the roots install and I add the following to your wp-config.php on your development installation:
define('WP_ENV', 'development');

should this be defined in a different way/differently...

**** error 3 ******
all of the css/js calls are to the old roots files (main.css, etc...)

***** error 4 ***** 
page loads break...
base.php calls to echo some arrays (roots_main_class, roots_sidebar_class):
      <main class="main <?php echo roots_main_class(); ?>" role="main">
        <?php include roots_template_path(); ?>
      </main>
      <?php if (roots_display_sidebar()) : ?>
        <aside class="sidebar <?php echo roots_sidebar_class(); ?>" role="complementary">

should echo variable $roots_main_class or roots_main_class['class'] or something...

**Comment by johnadapt** [comment]
I'm still learning how to help, so if this is not the right way to do this, let me know... :)

**Comment by johnadapt** [comment]
for error 3,
 -it needs to call app.css, not main.css
 -call script.js (instead of scripts.js) or rename... same with the script.js.map
 -modernize is located here: /assets/js/vendor/modernizr.js 
   not here: /assets/js/vendor/modernizr/modernizr.js

**Comment by Mte90** [comment]
i need to test completally the new version. I'm sorry for all this problems

**Comment by Mte90** [comment]
fixed other problem and template tested :-)
